### ISSUE TITLE
embed workflow version number

### ISSUE THREAD

**Issue by konoui** [konoui/alfred-tldr#14]
related #8

**Comment by luckman212** [comment]
hey @konoui ... strange, I got a notification the other day about a 0.6.1 version being released, but now I can't see any evidence of it ever existing. Was that me temporarily transporting to a parallel universe 🚀  👽  or was there a problem with that release? 
thanks

**Comment by konoui** [comment]
Hi @luckman212 ,
v0.6.1 was disappeared 👽. 
I failed to release the version. I am fixing the release problem.
Next release will be success!!

**Comment by luckman212** [comment]
👽 sounds good

**Comment by konoui** [comment]
v0.6.1 is just released 👽👽.
