### ISSUE TITLE
Remove the {{ }}

### ISSUE THREAD

**Issue by chrisgrieser** [konoui/alfred-tldr#16]
I know that they are there to signify input, but I also feel like that they unnecessarily reduce readability.

Maybe there is a why to make them more readable, e.g. uppercasing the content?

**Comment by konoui** [comment]
Thank you for your proposal!
I agree with you.

Currently, the workflow adopts [original command format using `{{}}`](https://github.com/tldr-pages/tldr/blob/main/CLIENT-SPECIFICATION.md#page-structure)

I will be able to introduce format option via alfred environment variable.

original
```
tar czf {{target.tar.gz}} --directory={{path/to/directory}} .
```

e.g.) remove option
```
tar czf target.tar.gz --directory=path/to/directory .
```

e.g.) uppercase option
```
tar czf TARGET.TAR.GZ --directory=PATH/TO/DIRECTORY .
```

e.g.) single option
```
tar czf {target.tar.gz} --directory={path/to/directory} .
```

I think uppercase option is most readable of them.
If you have any other ideas, please let me know.

**Comment by chrisgrieser** [comment]
Great, thanks for the quick commits already 🤗 

I'd say uppercase them. This would also be in line with how e.g. the Pandoc documentation does it: 
<img width="903" alt="Screenshot 2021-08-13 14 58 55" src="https://user-images.githubusercontent.com/73286100/129360702-211d8209-bb63-44fc-912b-98ae131767b8.png">

**Comment by konoui** [comment]
OK, I decide to enable uppercase by default instead of `{{}}`.
It will take a few days to release new version.
Thanks!!

**Comment by chrisgrieser** [comment]
No hurry :)

Thank you for this useful workflow!

**Comment by konoui** [comment]
I implemented the feature.
I adopted "single" for default behavior not "uppercase" to avoid confusing as some commands uses uppercase for non-user input parameters with user input parameters.
If you want, please set "uppercase" value for [TLDR_COMMAND_FORMAT variable](https://github.com/konoui/alfred-tldr/blob/main/doc/CONFIGURATION.md).

**Comment by chrisgrieser** [comment]
great, thanks!
