### ISSUE TITLE
FR: selecting description with link should open the link

### ISSUE THREAD

**Issue by chrisgrieser** [konoui/alfred-tldr#17]
Most results have a short description with an URL for further information as the first result. A bit counterintuitively, that first result contains an URL, but you cannot select the result with `return`. 

<img width="1018" alt="Screenshot 2021-08-14 01 19 20" src="https://user-images.githubusercontent.com/73286100/129430173-2ad9ae89-1e26-458e-9f0e-c3d142ff717b.png">

I'd suggest to make it possible to directly open the URL in the first result.

**Comment by konoui** [comment]
It seems useful!
In my investigation, most commands have more information URL.
I will implement the feature.

```
find ./pages -name '*.md' -type f | wc -l
2289

grep -L "More information:" ./pages/**/*  | wc -l
783
```

e.g.) command that does not have more information URL
https://github.com/tldr-pages/tldr/blob/main/pages/linux/lsblk.md

**Comment by konoui** [comment]
I implemented the feature. 
We will be able to open URL with [`command` + `enter(return)`](https://github.com/konoui/alfred-tldr/blob/main/doc/CONFIGURATION.md) for next release.
I did not adopt enter only to open URL to avoid to press enter and launch the browser accidentally.

**Comment by chrisgrieser** [comment]
great, thanks a lot for this useful workflow!
