### ISSUE TITLE
"vv0.8.0"

### ISSUE THREAD

**Issue by luckman212** [konoui/alfred-tldr#20]
Thanks for the workflow update! @konoui 

One small nitpick...
Since you tag your release with the "v" prefixed to the string e.g. `v0.8.0` the Makefile that inserts the version causes Alfred to display double V as `vv0.8.0`

you could fix this either by omitting the `v` or by stripping it during the build phase
I made a PR for the latter... #19

![image](https://user-images.githubusercontent.com/1992842/130325998-e693553c-7a13-45ab-8082-1a83435e4606.png)

**Comment by konoui** [comment]
I really appreciate your cooperation!
