### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by NicoleMayer** [konoui/alfred-tldr#4]
When I enter "tar", I only got a list of commands like this:

![image](https://user-images.githubusercontent.com/32037406/102860747-66177400-4469-11eb-8813-2a9c793d84d3.png)

As you can see, the tldr's color doesn't change. When I hit enter, everything will go.

**Comment by konoui** [comment]
Thank you for reaching out to me.
I understand your issue bellow.
* `tldr tar` does not show tar command information.
* If you hit enter, the workflow shows tar command information.

The behavior is something strange...

Could you please give me following information for further investigation?
- Alfred version, 3 or 4?
- Following command results
    - `tldr --update` and hit enter`
    - `tldr tar -p common`
    - `tldr tar -p osx`

**Comment by NicoleMayer** [comment]
Sorry, the first one "tldr tar does not show tar command information." is right, but the second one "If you hit enter, the workflow shows tar command information." is not true. I mean the Alfred Input Box will disappear.

I use Alfred 4. A strange thing is when I tried `tldr tar -p common` again after `tldr --update`, I got an error:

```
ERROR: tldr[Script Filter] Code 1: {"items":[{"title":"Fatal errors occur","subtitle":"unexpected EOF","icon":{"path":"/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertCautionIcon.icns"},"valid":true}]}
```

After a while, I tried it again and no errors happened. But I still got the same results as `tldr tar`:

![image](https://user-images.githubusercontent.com/32037406/102888219-4bf28b80-4493-11eb-8922-159777075f9d.png)

Similar case for `tldr tar -p osx`. 

So my problem is the workflow only shows different commands match what I have enter and it doesn't show sth like `tar tvf {{source.tar}}` that teaches me how to use a command.

**Comment by konoui** [comment]
Thank you for your information!
The behavior means that the workflow could not find `tar.md` file.
The workflow locates page data into `Workflow Data/dev.konoui.alfred-tldr/.alfred-tldr` directory by default.

Please confirm that `tar.md` exists or not.
```
$ find ~/ -name tar.md                                                   
/Users/<XXXX>/Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/.alfred-tldr/pages.de/common/tar.md
/Users/<XXXX>/Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/.alfred-tldr/pages.fr/common/tar.md
/Users/<XXXX>/Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/.alfred-tldr/pages.es/common/tar.md
/Users/<XXXX>/Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/.alfred-tldr/pages.pt_BR/common/tar.md
/Users/<XXXX>/Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/.alfred-tldr/pages/common/tar.md
/Users/<XXXX>/Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/.alfred-tldr/pages.ru/common/tar.md
```

The workflow showed suggestions such as`tar`, `apt add repository` and `transmission remote` etc..
This means suggestions file (`index.json`) exists in your data directory.

```
$ ls ~/Library/Application\ Support/Alfred/Workflow\ Data/dev.konoui.alfred-tldr/.alfred-tldr/index.json
'/Users/<XXXX>/Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/.alfred-tldr/index.json'
```

**Comment by NicoleMayer** [comment]
The page data is corrupted and this is the root cause of my problem. Thank you for your help! I really like this workflow!

**Comment by konoui** [comment]
OK!
I close this issue. If you face with new issue, please create new one.
