### ISSUE TITLE
failed on apple silicon 

### ISSUE THREAD

**Issue by YUX** [konoui/alfred-tldr#5]
I tried to download it from release and built on my m1 Mac, but both end in the same result 

<img width="623" alt="Screen Shot 2021-01-19 at 15 14 00" src="https://user-images.githubusercontent.com/10670661/105000164-f77a0600-5a68-11eb-902c-24e2e08903ee.png">

**Comment by konoui** [comment]
Thank you for reaching out to me.
Sorry for the late response.

I've not prepared a workflow for m1 yet. I will provide it in new release!

However, if you build the workflow on your computer, it should work fine.
The error you provided means that workflow could not find command file.
Could you please give me following information for further investigation?
* Alfred version, 3 or 4?
* full error message
* following command results
`find~/ -name tar.md`


The workflow downloads zip file and unzip to workflow data directory.
In your case, workflow data directory may be corrupted.
```
$ find ~/ -name tar.md
/Users/<username>/Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/data/pages.de/common/tar.md
/Users/<username>/Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/data/pages.fr/common/tar.md
/Users/<username>/Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/data/pages.es/common/tar.md
```

**Comment by konoui** [comment]
I identified a root cause.
I am going to release fixed workflow. but m1 workflow is not provided. 
Could you please build it on your computer.

**Comment by YUX** [comment]
I'm using Alfred 4.3.1 [1214] Universal Build

```
/Users/yux//Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/data/pages.de/common/tar.md
/Users/yux//Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/data/pages.fr/common/tar.md
/Users/yux//Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/data/pages.es/common/tar.md
/Users/yux//Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/data/pages.pt_BR/common/tar.md
/Users/yux//Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/data/pages/common/tar.md
/Users/yux//Library/Application Support/Alfred/Workflow Data/dev.konoui.alfred-tldr/data/pages.ru/common/tar.md
```

**Comment by YUX** [comment]
hi I just rebuild it with your recent commit, now here is the m1 native build version:
[tldr.alfredworkflow.zip](https://github.com/konoui/alfred-tldr/files/5886970/tldr.alfredworkflow.zip)
 and all work smoothly. cheers 🍻

**Comment by YUX** [comment]
btw, the intel x86 version also works smoothly via Rosetta 2.
