### ISSUE TITLE
Auto-Update Capability

### ISSUE THREAD

**Issue by xilopaint** [konoui/alfred-tldr#8]
Does this workflow have auto-update capability?

**Comment by konoui** [comment]
Hi, 
Thank you for reaching out to me!

> Does this workflow have auto-update capability?

No, we need to execute install command again.
I do not have ETA but I want to implement the feature!
Please keep the issue open.

**Comment by xilopaint** [comment]
You can easily implement an auto-update feature integrated with GitHub releases using [OneUpdater](https://github.com/vitorgalvao/alfred-workflows/tree/master/OneUpdater) or even the [AwGo](https://github.com/deanishe/awgo) library.

**Comment by luckman212** [comment]
Related suggestion:  in lieu of an auto-update, it would be useful if the workflow at least included the version in its distribution...

![image](https://user-images.githubusercontent.com/1992842/112859366-c2012280-9080-11eb-866e-914f86d93c1d.png)

**Comment by xilopaint** [comment]
The auto-update feature can be implemented in 5 minutes using OneUpdater.

**Comment by konoui** [comment]
Hi,
Sorry for late response.
I've implemented auto-update feature without OneUpdater.
I think OneUpdater is great but on my environment it does not work well due to security problem.My environment is a little unusual...
If the feature that I implemented is insufficient, I will reconsider ways of auto-update.

**Comment by xilopaint** [comment]
@konoui please, consider to adopt this suggestion so we can know what workflow version we are running.

> Related suggestion: in lieu of an auto-update, it would be useful if the workflow at least included the version in its distribution...
> 
> ![image](https://user-images.githubusercontent.com/1992842/112859366-c2012280-9080-11eb-866e-914f86d93c1d.png)

Also, if it can be useful for your implementation, you can retrieve the workflow version by the [alfred_workflow_version](https://www.alfredapp.com/help/workflows/script-environment-variables/) environment variable.

**Comment by konoui** [comment]
Thank you for your suggestions.
I will embed version number with workflow configuration of info.plist for next version!

**Comment by xilopaint** [comment]
> Hi,
> Sorry for late response.
> I've implemented auto-update feature without OneUpdater.

Is it really working? I got this output after the release of v0.6.1:

```
[10:51:07.809] tldr[Script Filter] Queuing argument ''
[10:51:07.840] tldr[Script Filter] Script with argv '' finished
[10:51:07.843] STDERR: tldr[Script Filter] [INFO] no newer version exists
[10:51:07.844] tldr[Script Filter] {"items":[{"title":"Please input a command","subtitle":"e.g.) tldr tar e.g.) tldr --help","valid":false}]}
```

**Comment by xilopaint** [comment]
Btw you don't have to type a `v` ahead of the version on the configuration sheet or you will have a double `v` on the workflow editor:

![Screen Shot 2021-04-17 at 11 00 05](https://user-images.githubusercontent.com/11052366/115115762-9a5cf600-9f6c-11eb-8a4d-0de8c0f0eb00.png)
